spring:
  application:
    name: library-service
  config:
    import: optional:configserver:http://127.0.0.1:8888

application:
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    topic-id: main-topic
  open-api:
    server: http://127.0.0.1:8081