logging:
  level:
    com.elyashevich.book: DEBUG
spring:
  application:
    name: book-service
  config:
    import: optional:configserver:http://127.0.0.1:8888
application:
  kafka:
    topic: order
    replica: 1
    partition: 1
  open-api:
    server: http://127.0.0.1:8082