spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/users
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  springdoc:
    packagesToScan: com.elyashevich.authentication
    api-docs:
      enabled: true
      path: /v3/api-docs/auth
    swagger-ui:
      path: /v3/api-docs/auth

server:
  port: 8083
