server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: book-service
          uri: lb:http://book-service
          predicates:
            - Path=/api/v1/books/**
        - id: library-service
          uri: lb:http://library-service
          predicates:
            - Path=/api/v1/library/**
        - id: authentication-service
          uri: lb:http://authentication-service
          predicates:
            - Path=/api/v1/auth/**
      cors-configurations:
        '[/**]':
          allowedOrigins: "*"
          allowedHeaders:
            - "*"
          allowedMethods:
            - "GET"
            - "POST"
            - "PATCH"
            - "DELETE"
            - "OPTIONS"
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET,POST,PATCH,DELETE