server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: book-service
          uri: lb:http://BOOK-SERVICE
          predicates:
            - Path=/api/v1/books/**
        - id: library-service
          uri: lb:http://LIBRARY-SERVICE
          predicates:
            - Path=/api/v1/library/**